### ISSUE TITLE
Mergefield format support

### ISSUE THREAD

**Issue by tarnap** [senny/sablon#103]
Does sablon support merge field date formatting?

A field with a date format should be supported:
```
{ MERGEFIELD =some_date \@ format \* MERGEFORMAT }
```

There's no error while processing a template with such a field, but the field is not replaced in the resulting document.

**Comment by stadelmanma** [comment]
Hi Pablo, Sablon uses a rather specific pattern for merge fields so anything with a format directive will not match. Additionally, supporting the large range of format specifiers available would be quite a task when in most cases you can apply the formatting on the Ruby side which allows for far flexibility and error handling (i.e. nil vales). 

Is there any reason you can't format your date ahead of time? i.e. `context = { some_date: Time.now.strftime('%b %d, %Y') }`

**Comment by stadelmanma** [comment]
I can see where the date format varying across and within templates adds a bit of complexity. Another work around might be to wrap those dates in a decorator type of object. Then instead of setting the format in the merge field you would call the appropriate method on your decorated date. Unfortunately as of right now Sablon doesn't support arguments when calling methods on a context object (it's tricky to implement). So depending on your situation you might need quite a few decorator methods although they would probably be one-liners at least. 

I don't think this is something we could incorporate into the gem itself. Our goal is to have as much logic as possible applied on the Ruby side because debugging templates is a pain. However, looking at the code structure I don't believe it would be impossible for you to implement it yourself. First you would need to generalize the `KEY_PATTERN` constant in Sablon::Parser::MailMerge::MergeField to capture that format specification and add an attribute to the class to store it on the "field" instance generated. That field instance is used when inserting text into the template in the Sablon::Statement::Insertion class (defined in lib/operations.rb). You would add your custom date formatting logic in Insertion#evaluate.

**Comment by stadelmanma** [comment]
Closing as resolved, the semi-related feature of allowing method calls with arguments would be a separate issue+PR.
