### ISSUE TITLE
Colspan has not effect

### ISSUE THREAD

**Issue by ahmedelmahalawey** [senny/sablon#104]
I have been trying to merge multiple cells in table, so when i used colspan it seems that it doesn't have effect, is there any way to apply that?

**Comment by stadelmanma** [comment]
Hi @ahmedelmahalawey colspan and rowspan are supported, although rowspan couldn't be done using the normal "HTML way". Both must be applied as part of the `style="..."` attribute on the HTML tag. Although in principle it wouldn't be hard to check for the properties directly on the node it just wasn't implemented that way. 

```HTML
<table style="border: 1px solid #000000; width: 4000dxa">
    <caption>Col/Row Span Example</caption>
    <tr>
        <th>Head Cell 1</th>
        <th>Head Cell 2</th>
        <th>Head Cell 3</th>
    </tr>
    <tr>
        <td style="colspan: 2">Data Cell 1</td>
        <td style="rowspan: start">Data Cell 3</td>
    </tr>
    <tr>
        <td>Data Cell 1</td>
        <td>Data Cell 2</td>
        <td style="rowspan: continue">Data Cell 3</td>
    </tr>
    <tr>
        <td>Data Cell 1</td>
        <td>Data Cell 2</td>
        <td style="rowspan: end">Data Cell 3</td>
    </tr>
    <tr>
        <td>Data Cell 1</td>
        <td>Data Cell 2</td>
        <td>Data Cell 3</td>
    </tr>
</table>
```

Supporting `rowspan="#"` would take considerably more effort, since in HTML the spanned cells aren't present so they would need to be added into the HTML document at the correct locations. Then you also run into edge cases of how to handle things when the table is not formatted correctly.

**Comment by stadelmanma** [comment]
Closing this as resolved. Support for a number valued rowspan would be a separate feature request.
