### ISSUE TITLE
undefined method `next_element' for nil:NilClass with image renderring

### ISSUE THREAD

**Issue by comictvn** [senny/sablon#109]
## Hi everyone 
I have got a problem with image renderring 
this is my template 
<img width="1229" alt="screen shot 2018-06-11 at 5 25 35 pm" src="https://user-images.githubusercontent.com/6270931/41227110-eb0dd51e-6d9d-11e8-8f32-9522937c5ed6.png">

https://drive.google.com/file/d/1gkLScWfJI1BClb5EKgW67fb3Qcx51FJc/view?usp=sharing
is there anyone same the issue ?

**Comment by stadelmanma** [comment]
Hi @comictvn after unzipping the document and looking at the relevant portion I don't see anything obviously wrong with the XML so this looks like it might be a bug. 

Your template is quite complex which makes things hard to test from that angle. Do you think you could pare it down to a minimal example that reproduces the issue and provide a sample context to use with the template? (as for images I can replace whatever file you use with something local I just want the hash structure to copy and paste into a test script)

**Comment by stadelmanma** [comment]
After doing some investigating I think this is due to the fact I have an each block and its contents all within a single paragraph and then those children get wrapped in a "tmp" node instead of whatever parent node type was being used before. This was discovered from a WordML insertion bug that happened when an entire conditional appeared within a single paragraph.

I'll need to test images specifically later on after I fix the bug with WordML.
