### ISSUE TITLE
Simplify editing the Word template by using another field name convention

### ISSUE THREAD

**Issue by huerlisi** [senny/sablon#117]
Creating a Word template for use with Sablon is a bit complicated due to the multiple steps needed to enter the fields. This is partly due to the need for special characters like `=` and `.`.

I tried to simplify this for other users by preparing a CSV with available fields as the first line that could be added as a data source. But the fieldnames get simplified (like `=person.name` => `personname`). In some quick tests most special characters got removed, but at least underscores `_` were kept.

What do you think about introducing a convention to support field annotations using underscores (and possibly other halve-special characters we find)? I guess we might need to introduce a flag to select the annotation convention to ensure backward compatibility...

In the simplest way it could go like
* `=person` => `_person`
* `=person.name` => `_person__name`
* `people:each` => `people__each`

The convention above is just a possible idea, we might well come up with some more clever convention;-)

As said, this would allow to pass a simple CSV (or XLS or whatever) file to people that should create templates so they can assign it as an address book and use the built-in, quick'n'easy field insertion menu action.

Thanks a lot for this wonderful gem!

**Comment by senny** [comment]
Hi @huerlisi 

Sablon is designed for technical people. The design of the syntax reflects that some programming background is necessary or at least helpful in understanding all constructs. I don't think the project needs to support such an alternative syntax by default. Your use-case with the CSV seems quite specific

Having said that, I think it should be possible to exchange or at least patch in that behavior without having to change the whole codebase. Have a look at [this file](https://github.com/senny/sablon/blob/master/lib/sablon/processor/document/field_handlers.rb). I think it should be possible to extend the syntax using these `field_handlers`. I haven't worked on the gem's code much lately, @stadelmanma can probably give better advice.

Thanks for the feedback and let me know if you find your way around extending the grammar.

**Comment by stadelmanma** [comment]
Adding custom `FieldHandler` subclasses is a way to address this need. Although to go that route for text insertion you'll need to re-convert the underscore syntax back into normal "dot" syntax (i.e. object__method => object.method). Otherwise the code that does hash lookup/method calls won't function correctly. For text insertion you'd do that in the `build_statement` method prior to calling `Expression.parse`.

Another route that may or may not be easier is to preprocess the template prior to passing it to Sablon. In that preprocessing step you'd do the same field name convention conversion I mentioned above. 

I'm not sure which one is better. I'd probably lean towards adding `FieldHandlers` to avoid adding another step to the process. Especially if most of your template creators are non-technical or on systems that aren't as Ruby friendly (i.e. Windows).

**Comment by huerlisi** [comment]
Hi @senny @stadelmanma thanks a lot for the feedback! I'll try to build something using your input.

**Comment by stadelmanma** [comment]
Closing this as resolved.
