### ISSUE TITLE
Don't know how handle HTML tag: firstname

### ISSUE THREAD

**Issue by MGStudio** [senny/sablon#122]
Hello,

I'm using your library to generate docx documents from a database. 
In this database some field are riched text so i'm using
`Sablon.content(:html, html_content)`
In the html content it can be a content like this one:
```
<p> First sample </p>
<p> Lorem ipsum <firstname> </p>
```

Problem is that the library try to transform <firstname> as an html component but it's not.

Is it possible indicate to the component to ignore `<firstname>` ? 
thx for your help , and good job for the lib ;)

**Comment by stadelmanma** [comment]
Hi @MGStudio unfortunately XML parsing is done via Nokogiri and it picks up all tags (regardless if they are part of the HTML spec), so that isn't something we can change directly. Your best bet might be to use HTML entities instead i.e. `&lt;firstname&gt;` which should be passed through properly (if not then thats a bug and please let us know).

In terms of readability and convenience this isn't ideal but you could write a small preprocessor function to do those replacements for you prior to adding the value to the context hash.

**Comment by MGStudio** [comment]
Ok thanks for the advice
