### ISSUE TITLE
Adding html table results in table with no width

### ISSUE THREAD

**Issue by arvanasse** [senny/sablon#126]
I'm adding Sablon.content with an html table.  The resulting table has columns with 0.1inch width.  I have attempted to add width on the table element (```<table style="width: ...">```) and also on the td/th elements.  I've used a variety of width values.  Most recently, I traced the code enough to see that it attempts to set the table/column width using dxa units, so my values were 1000 (columns) to 5000 (tables) hoping to see a table roughly 7 inches wide.  None of the values has changed the table rendered into the document.

**Comment by stadelmanma** [comment]
@arvanasse can you provide more details? For example I have a table defined as such and it fits to the content contained.

```HTML
<table style="border: 1px solid #FF0000">
    <caption style="caption-side: bottom; highlight: cyan; text-align: center">
        Table 1: Example With Formatting
    </caption>
    <thead>
        <tr style="border: 1px solid #FF00FF">
            <th>Head Cell 1</th>
            <th>Head Cell 2</th>
        </tr>
    </thead>
    <tbody>
        <tr style="border: 1px solid #0000FF">
            <td style="color: #FFAA22">Data Cell 1</td>
            <td style="background-color: #123456">Data Cell 2</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td>Data Cell 3</td>
            <td>Data Cell 4</td>
        </tr>
    </tfoot>
</table>
```

See more HTML examples: test/fixtures/html/html_test_content.html

**Comment by arvanasse** [comment]
@stadelmanma What's been interesting is that the document formatting is fine _when the document is opened in Word_.  I'm working on a macbook pro without Word installed.  The Pages app typically opens Word docs without any issue.  I'm not sure what would be required to make Sablon-generated docs more portable.

**Comment by stadelmanma** [comment]
Ah, so unfortunately MS Word doesn't completely follow the OOXML spec and they have *alot* of exceptions. I suspect this must be one of them since I have the same issue when I open the document using libreoffice at home. I suspect Pages must follow the OOXML spec to the letter (I'm pretty sure libreoffice does)

So the main way to debug this issue would be for you to generate a very simple 4 cell table (table XML is verbose so you don't want something big) that exhibits the problem shown. Unzip the DOCX file and copy out the relevant table's XML (contained in word/document.xml). 

Then you will want to fix the table in Pages and do the same steps as above to see what differs between MS Word's table XML and the Page's XML.

Portability is nice when it's possible but formal support for non MS Word applications is not planned, I simply don't have the time (and I'm not 100% sure of the "need" for it either).
