### ISSUE TITLE
Include assert_docx_equal in packaged gem

### ISSUE THREAD

**Issue by pimlottc-gov** [senny/sablon#134]
The `assert_docx_equal` helper in test/test_helper.rb would be useful for client applications that are using the Sablon library.  It would be nice if it were included in the packaged gem to avoid having to copy the code manually!

**Comment by stadelmanma** [comment]
I can make the change easily since I do agree that there is some utility in allowing someone to test their document generation. The big caveat with this is that simply opening and resaving a document without "making" any changes can be enough to make the assertion fail. This is because MS Word does some of it's own internal mangling/cleanup as needed.

**Comment by pimlottc-gov** [comment]
Yeah, we've definitely found that the expected document is very "fragile", especially as the diff includes metadata including edit times.  But it's definitely better than nothing, and it helps us make sure the rest of our app is working properly, as we do some processing to generate the context values that get sent to Sablon.
