### ISSUE TITLE
Wanted: pre-Tag / monospace text style

### ISSUE THREAD

**Issue by blacklist-arcc** [senny/sablon#152]
Some of my document/reporting process using this nice gem. I missed the possibility to add text in monospace or `<pre>`  style in order to add some code samples into the document. It would be nice to get this feature or any hint where i can start modifying the config file.

Thank you.

**Comment by stadelmanma** [comment]
I'm not sure exactly what would need to be done but essentially you'd want to register a new `inline` type HTML tag that defines the desired font family via WordML properties since I don't have a CSS style convert defined for font families. 

I think this is the XML that needs generated.
```xml
<w:rPr>
    <w:rFonts w:ascii="Courier New" w:cs="Times New Roman" />
</w:rPr>
```
In terms of configuration I think this is the definition you'd want to use (subbing in your desired font familes):
```ruby
Sablon.configure do |config|
  config.register_html_tag(:pre, :inline, 
    properties: { rFonts: {ascii: "Courier New", cs: "Times New Roman"} })
end

```
Some additional references:
https://github.com/senny/sablon/blob/master/test/configuration_test.rb
https://github.com/senny/sablon/blob/master/lib/sablon/configuration/configuration.rb#L85

**Comment by blacklist-arcc** [comment]
Nice. Works flawless! Thanks for your fast reply. Awesome project!
