### ISSUE TITLE
Can i access a specific item in an array?

### ISSUE THREAD

**Issue by mroliveira7** [senny/sablon#155]
Im passing an array and i want to print some itens like:
`«=products[0].cod»`
Is that possible?

**Comment by stadelmanma** [comment]
Apologies for the late answer, I don't know off the top of my head since I've never tried it but it might be possible. Sablon supports Hash access via `[...]` so it might _happen_ to also work for arrays. Instead I would probably do `«=products.first.cod»` if you are usings rails or make the "first item" an explicit entry in the context hash since you want to do special things with it.

**Comment by mroliveira7** [comment]
I tested it but i was not able to do it. Anyway i convinced my coworkers to not use it like that.
Thanks!
