### ISSUE TITLE
Dynamic Table Columns

### ISSUE THREAD

**Issue by jppribeiro** [senny/sablon#158]
Hey there,

I'm using this gem to generate docx files where I have a table that is generated based on a dataset. I can generate rows dynamically with no problem. 
I'm using loops and conditionals using merge fields inside the table on the template.
But I also need to generate columns based on the dataset. From what I understand we don't actually have columns but cells inside rows. I tried to apply a conditional merge field just like I did for rows, but it did not work.

What's the best approach to accomplish this?

Thanks a lot!

**Comment by stadelmanma** [comment]
@jppribeiro I'm not sure home complex your formatting is but I would probably use HTML insertion instead. Basically you'd need a "pre-processing" step where you generate the desired table in HTML and then use that in your context instead of trying to do it with loops.

Off the top of my head I don't know if it's possible to generate extra columns in a for loop since I don't remember the XML format for tables. Even if the XML is agreeable it might be hard to get your merge fields in the right places.

**Comment by jppribeiro** [comment]
@stadelmanma That's exactly what I decided to do. I'm building the table structure with Nokogiri, converting it into html and using that in the context.

Thanks for answering so fast!

**Comment by stadelmanma** [comment]
Glad you found a working solution. HTML insertion isn't perfect but the code I've written that uses sablon takes advantage of it extensively (actually, excessively).
