### ISSUE TITLE
MailMerge fields not getting filled by data if inserted with Word/Insert tab/Quick Parts/Field/MailMerge field 

### ISSUE THREAD

**Issue by jan-kaczorowski** [senny/sablon#25]
If I get this straight, one should be able to create a new Word docx document as a template, insert some mailmerge fields, name them correctly, and sablon is supposed to fill those fields with data, just like its described in the gem page.

However, when I try to add a merge field via Word -> Insert tab -> Quick Parts -> Field -> MergeField (which seems to be the most convenient way to change any existing, well formated doc into a template for sablon) and name them "myfieldname" or "=myfieldname" (tried both), they are not being filled with data, and no error is thrown. Not certain if they are being correctly noticed by sablon either. In MS Word, fields display as mailmerge fields «myfieldname» or, (if you click Alt+F9) - { MERGEFIELD myfieldname } which looks just fine to me.

The curious part is that if you use this wizard you have in the Mailings tab->Start Mail Merge, to insert mailmerge fields in the template, it works properly - the field are indeed getting filled with data by sablon!

It would seem like the wizard is creating different XML tags, than just using Insert->Field->MergeField....

Any suggestions?

**Comment by senny** [comment]
This should work... Would you mind uploading the template and sablon script, wich are not working for you?

**Comment by jan-kaczorowski** [comment]
i tried to recreate the bug in several scenarios, and came across even more quirks. Two things suprized me really in this text: First, Now it would seem like adding a QuickParts-> Mergefield works provided it has an equal sign, but doesnt work if you make the field just adding the code. Tried it before, and failed. Second Mail Merge wizard fields did't got filled with text.
I'll do some more testing later on. 
[sablon_test_script.rb.txt](https://github.com/senny/sablon/files/71779/sablon_test_script.rb.txt)
[test_output_file_2.docx](https://github.com/senny/sablon/files/71780/test_output_file_2.docx)
[template-not-working2.docx](https://github.com/senny/sablon/files/71781/template-not-working2.docx)

**Comment by senny** [comment]
I looked at the template and it looks to be in the wrong format. When I try to open it (I'm on a Mac using Word for Mac) I get the following errors:

![screen shot 2015-12-24 at 17 27 05](https://cloud.githubusercontent.com/assets/5402/11996480/237d1d10-aa64-11e5-8fd0-3498ba0774f8.png)

![screen shot 2015-12-24 at 17 27 14](https://cloud.githubusercontent.com/assets/5402/11996482/2ba2a118-aa64-11e5-8c2b-91a4f8c273c4.png)

I was able to open the document in some kind of recovery mode and could look at the fields. None of them had the right format necessary for Sablon. With a couple of modifications I got some of the fields working:

![screen shot 2015-12-24 at 17 35 29](https://cloud.githubusercontent.com/assets/5402/11996516/c387f42e-aa64-11e5-84d6-d9a2711f74a6.png)

![screen shot 2015-12-24 at 17 34 04](https://cloud.githubusercontent.com/assets/5402/11996497/8e0542c0-aa64-11e5-80ac-b00157ea473e.png)

The fields in section one and two look right. But the `MERGEFIELD` code is not quite correct. A valid code looks something like this: `MERGEFIELD =myfield6 \* MERGEFORMAT`. There is exactly one space after `MERGEFIELD`, then an equal sign followed by the name of the field. In one instance the code in your field was quoted with `"` and the other one had additional whitespace.

Sablon could be more forgiving on the whitespace. I'll see if I can write a patch for that. Otherwise it looks like you just need to tweak your template a bit. Note that no Mail Merge wizard is required. You don't want to link your document to a database.

I hope that helps. Let me know if you got it working or if you have further questions.

**Comment by jan-kaczorowski** [comment]
Those hints of yours made me experiment some more with the template and eventually I managed to get it all to work! Thank you so much! 

The three fields inserted with the Quick Parts feature work just fine with the MERGEFORMAT enabled and equal sign as a prefix. Without MERGEFORMAT however they don't seem to work (which is just fine, since in 99% cases one probably does want them to retain formatting).

Also, the hand-written Merge Field codes seem to work properly just fine AFTER you press F9 (Update field) after writing each of them (which probably explains why third of them failed to work in my file, despite looking OK).

**Comment by senny** [comment]
@jan-kaczorowski yea, running "Update Field" is important to get the markup right. Glad you got it working. I'm closing this issue.
