### ISSUE TITLE
JRuby Support

### ISSUE THREAD

**Issue by veered** [senny/sablon#27]
I've been having trouble running Sablon in JRuby. The first problem was that JRuby doesn't support `redcarpet` (because it has native extensions) so I replaced it with `kramdown`, which seemed to work fine. Here is the [diff](https://github.com/qualialabs/sablon/commit/f3676998f21aabe88bd1068ae867346a1d0de55d) for that change. The second problem is much more obscure and seems to be caused by a difference in behavior between the Ruby and JRuby versions of Nokogiri. Sablon cannot properly render looped fields under JRuby. Here is the relevant portion of the [stacktrace](https://gist.github.com/veered/749ac86311987907085a). I have banged my head against this problem for a while so any advice is welcome.

**Comment by senny** [comment]
@veered I had a quick look and can confirm that JRuby's nokogiri definitely has some differences that make Sablon unsuable at the moment.

Regarding the Redcarpet, Since using markdown content is deprecated anyway it's probably better to remove it completely than replace the renderer with `kramdown`.

The Problems seem to be related to namespaces in the xml document but I didn't have time to collect any specifics. I don't use JRuby so this doesn't have a high priority for me. If you interested in working on this that would be great.

**Comment by senny** [comment]
@veered any updates on this one? I have not looked into supporting JRuby at all. Let me know if you have made some progress on that front.

**Comment by veered** [comment]
I ended up using `rjb` to communicate with the JVM instead of JRuby

**Comment by senny** [comment]
I'm going to close this off for now. I will not be working on jRuby support but I'll gladly accept patches to get us there.

Thanks for reporting!
