### ISSUE TITLE
Numbering continues from previous list

### ISSUE THREAD

**Issue by larson004** [senny/sablon#53]
First of all, thanks for this awesome gem.
I came across this issue when generating a document today.

**Sablon Template**
```
«array_of_item:each(item)»
   «=item.text»
   «item.list:each(list_item)»
        1. «=list_item»
   «item.list:endEach»

«array_of_item:endEach» 
```

**Context**
```
array_of_item = 
[ { text: ‘List of colours’, list: [‘Red’, ‘Orange’] },
  { text: ‘List of shapes’, list: [ ‘Square’, ‘Rectangle'] } ]

```

**Output Doc**
```
List of colours
   1. Red
   2. Orange

List of shapes
   3. Square
   4. Rectange 
```

As you can see in the output document, the numbering in the second list continues from the previous. 
I understand that this might be an issue with how word handles numbering, rather than Sablon.

**Comment by senny** [comment]
I don't have access to Word at the moment to verify, maybe you can insert some kind of "break" into the template. Either a kind of paragraph break or maybe there's even a list reset thing. Try experimenting with the list definition a bit.

Sorry that I can't give you more specific assistance. In this case there's not much Sablon can do because it just reuses the word markup.

**Comment by larson004** [comment]
Closing this for now.
Will update this thread, once I get this resolved.
