### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by TheBerg** [senny/sablon#6]
Hey, this looks amazing! Great job.

Have you looked into Image support? I am looking at using this library and would really want image support. If you don't have anything in the works I can take a stab at it. :)

**Comment by diegoqlima** [comment]
Hi @senny @TheBerg ,

This solution is being developed?
If you need some help, I am available.

**Comment by senny** [comment]
@diegoqlima I'm not working on it and am not aware of ongoing work. Maybe @TheBerg can give you more details.

**Comment by TheBerg** [comment]
@diegoqlima Nope, I am not using this library right now. We hope to in the future though

**Comment by valgusk** [comment]
Please note that it is possible to use another approach. My project is highly dependent on the sablon and I had to implement image support.
https://github.com/valgusk/sablon/commit/20b83d29f262dc698aacd678e01f6f3a94a22e69
The thing is, currently I do not have time to document/refactor/write tests/make pull request and I do not know when/if I will. 
So it is entirely FYI. Feel free to use and author the code if it fits your ideas though.

To use this solution you have to insert image named 'variable_name.(png|jpg|bmp|jpeg)'in your document and then in context use e.g { variable_name: { png: some_file/some_path }}

In images descrition you can provide sizing config, e.g. !{ width: rect, height: auto }
possible in any combination values are width: rect/auto/left/right/middle and height: rect/auto/top/bottom/middle

**Comment by mateusnava** [comment]
Guys, I created a pull request adding a image support. The pr was based in kubido fork for this project.

**Comment by senny** [comment]
For reference #28

**Comment by rajeevkannav** [comment]
@senny @mateusnava @TheBerg anyone going to merge this must have feature?

People are waiting.... :)

**Comment by senny** [comment]
@rajeevkannav this sort of comment will get you nowhere. It's disrespectful to the people working on the feature and the maintainers. This is open source software. Instead of waiting feel free to implement missing functionality on your own.

Adding image support is complicated. I would rather not merge something that is half working. The use-cases I designed sablon for do not (yet) require image replacements. I understand other use-cases do. If we have a well working solution we will merge.

**Comment by rajeevkannav** [comment]
@senny Okey. Above one is deleted for obvious reasons.

**Comment by leandronsp** [comment]
Just commented on the #28 with a solution for images, because the PR isn't working for some. Also I tried other solutions proposed here and there, but none worked for me. 

I'll try to submit a new PR based on #28 in the next couple of days with some adjustments, fixes and more tests, but for now, my [fork feature branch](https://github.com/fullfabric/sablon/tree/image-support) has such fixes, it's working with images and it's sync with senny/master.

**Comment by gamesover** [comment]
Thank you all. It would be nice if this gem could add image supports. Since it is a very common requirement.

**Comment by gamesover** [comment]
@leandronsp , is it possible to resize the original image and put into word?

**Comment by leandronsp** [comment]
@gamesover Do you mean the original one (placeholder) or the context image which will replace the placeholder? 

The placeholder you can manipulate wherever before putting it into the word template. Then, within the word template, you are still able to resize the placeholder. 

But the final image to be used (the context) is not resized nor manipulated for now. Actually, I can't see the benefits of resizing the context image once the placeholder can be resized hence it will make the context image to have the exactly size of placeholder, as far as I have been tested.

**Comment by stadelmanma** [comment]
@senny (and anyone else that wants to weigh in) I have been reviewing how to add image support to sablon given that the recent changes remove most of the complexity added by PRs #28 and #54 in managing the rIds and adding new content to the zip archive. 

The current block structure used by the above PR's will be easy to add in but suffers from a requirement that the merge fields be inline with the image. This method can be available incase the end user needs to use a loop or if construct in the template with images. Oddly positioned images wouldn't make sense here because they would exist outside of the expression block.

A relatively simple fix that might work for positioned images is to add the proper "merge field" text to the `title` attribute of the placeholder image. A second parser would run after the initial work of the MailMerge parser is completed to collect all of the tags formatted like: `<wp:docPr id="4" name="Picture 4" title="@test.data.plot2"/>`. The `rId` of the `<a:blip r:embed="rId5"/>` tag would get updated as needed to the real image value. The title attribute can be easily set and updated in MS Word via the "Alt Text" tab on the formats pane.
