### ISSUE TITLE
Support for Legacy Form Fields

### ISSUE THREAD

**Issue by sashman** [senny/sablon#64]
Hey @senny,

First thank you very much for such an excellent gem!

My question is about other ways Word docs can be templated, in my instance Text Form Fields. The difference in the generated XML isn't too big as far as I can see, for example for a field with label "Fullname":
```
<w:r>
	<w:rPr>
		<w:b/>
		<w:sz w:val="36"/>
		<w:szCs w:val="36"/>
		<w:u w:val="single"/>
		<w:lang w:val="en-GB"/>
	</w:rPr>
	<w:fldChar w:fldCharType="begin">
		<w:ffData>
			<w:name w:val="Fullname"/>
			<w:enabled/>
			<w:calcOnExit w:val="0"/>
			<w:textInput/>
		</w:ffData>
	</w:fldChar>
</w:r>
<w:bookmarkStart w:id="1" w:name="Fullname"/>
<w:r>
	<w:rPr>
		<w:b/>
		<w:sz w:val="36"/>
		<w:szCs w:val="36"/>
		<w:u w:val="single"/>
		<w:lang w:val="en-GB"/>
	</w:rPr>
	<w:instrText xml:space="preserve">FORMTEXT </w:instrText>
</w:r>
```

Do you reckon it's worth me attempting an alternative parser for your gem? Or if you know an easy way for me to [convert Form Fields to Merge fields](https://stackoverflow.com/questions/45269649/convert-ms-word-legacy-text-form-field-to-mailmerge-field), that would also be great!

Thanks for your help in advance!

**Comment by senny** [comment]
Hey @sashman

In theory it is possible to build a second parser for Sablon. The internals are structured in a way that should make it possible to replace just the parsing and field replacement logic. However, I assume you have a bunch of existing documents that use these fields? In that case it's unlikely that the expressions match the Sablon grammar. While I can see adding a separate parser to Sablon, I don't think it makes sense to add different grammars. Simply because everyone with legacy documents would have different rules of how the fields were named.

If the WordML is close enough, you could attempt a script to convert your fields to MailMerge fields and also normalize the field text to match Sablons grammar.

I hope this helps. Let me know if I missed something or you have further questions.

**Comment by stadelmanma** [comment]
If you go the script route to convert all of your form fields to sablon-esque merge fields I would check and see if every text field is wrapped up in complex fields like the snippet above. If that is the case odds are you could pull out the parser logic used in Sablon to form the core of your conversion script since it already targets complex fields. Once you have the field you'll have to design your own rules for the conversion itself probably working with the `w:instrText` nodes. 

I think you would want to look for a structure similar to the following with your form fields being inside a `w:fldCharType="begin"` and `w:fldCharType="end"`set of tags. However, I've not worked with legacy form fields so I don't know if there are any differences (or inconsistencies).

```xml
<w:r>
    ...
    <w:fldChar w:fldCharType="begin" />
</w:r>
...
<w:r>
    ...
    <w:fldChar w:fldCharType="separate" />
</w:r>

...
<w:r>
    ...
    <w:fldChar w:fldCharType="end" />
</w:r>
```

**Comment by stadelmanma** [comment]
Closing this as semi-resolved. 
* It is possible to write a new parser class to build "fields" from form fields instead of merge fields.
* It is now possible to register new field handler's easily if the existing grammar of the form fields doesn't match what Sablon expects by default.
