### ISSUE TITLE
Is the equal sign before merge fields necessary?

### ISSUE THREAD

**Issue by skuark** [senny/sablon#72]
Hi!

We're integrating sablon in our application, but we're facing an issue with the typical Word Merge Fields Workflow. The idea is to follow a similar approach to the explained in this video: https://www.youtube.com/watch?v=G-pZKyG373s

So, we want to:

- Create an excel document with a unique row, where we include all the available merge fields available in our app.
- Use that excel document as a template for mail merge, so users would be able to compose a template in an easy way, using the Word utility to insert merge field), and simplify the interaction explained in [TEMPLATE.md](https://github.com/senny/sablon/blob/master/misc/TEMPLATE.md).

  ![](http://g.recordit.co/hFs3uDWZY6.gif)

The problem is that sablon requires an equal sign before the variable name for simple expressions, and Word doesn't allow to include special characters in the list of available fields. If you add an equal sign before the field in the excel template, Word simply ignores it.

I've been reviewing sablon source code, to try to understand why the equal sign is required before the variables, and as I understand, it's only to differentiate these expressions from complex expressions, as you can see in `sablon/lib/sablon/processor/document.rb`.

```ruby
def consume(allow_insertion)
  @field = @fields.shift
  return unless @field
  case @field.expression
  when /^=/
    if allow_insertion
      Statement::Insertion.new(Expression.parse(@field.expression[1..-1]), @field)
    end
  when /([^ ]+):each\(([^ ]+)\)/
    block = consume_block("#{$1}:endEach")
    Statement::Loop.new(Expression.parse($1), $2, block)
  when /([^ ]+):if\(([^)]+)\)/
    block = consume_block("#{$1}:endIf")
    Statement::Condition.new(Expression.parse($1), block, $2)
  when /([^ ]+):if/
    block = consume_block("#{$1}:endIf")
    Statement::Condition.new(Expression.parse($1), block)
  when /^comment$/
    block = consume_block("endComment")
    Statement::Comment.new(block)
  end
end
```

I was thinking that maybe it's possible to refactor that code to something like this:

```ruby
def consume(allow_insertion)
  @field = @fields.shift
  return unless @field
  case @field.expression
  when /([^ ]+):each\(([^ ]+)\)/
    block = consume_block("#{$1}:endEach")
    Statement::Loop.new(Expression.parse($1), $2, block)
  when /([^ ]+):if\(([^)]+)\)/
    block = consume_block("#{$1}:endIf")
    Statement::Condition.new(Expression.parse($1), block, $2)
  when /([^ ]+):if/
    block = consume_block("#{$1}:endIf")
    Statement::Condition.new(Expression.parse($1), block)
  when /comment/
    block = consume_block("endComment")
    Statement::Comment.new(block)
  else
    if allow_insertion
      Statement::Insertion.new(Expression.parse(@field.expression), @field)
    end
  end
end
```

I've done a quick test and it seems it works, but really I haven't analyzed the library in depth to determine if it could cause side effects (apart from the obvious, the lost of backward compatibility for previously generated templates). What do you think? Could you considerate a merge if I send a PR?

Thanks for your work!

**Comment by stadelmanma** [comment]
Hi @skuark I would say the biggest consequence of removing the leading equals sign is that it prevents the user from mixing sablon targeted merge fields with regular merge fields. 

Just out of curiosity have you tried quoting the merge field value in the excel cell? That might allow it to ignore the equals sign instead of thinking it's a formula i.e. `'=field_name` instead of `field_name`.

**Comment by paucc** [comment]
We did try the quote approach (`'=field_name`) but word doesn't add the equal sign when loading it.
cc @skuark

**Comment by skuark** [comment]
Yes, as @paucc says, we tried it. Word also has a UI to customize the list of fields, and it neither works:

![captura de pantalla 2017-10-05 a las 10 33 02](https://user-images.githubusercontent.com/454382/31217911-d55cd2f0-a9b8-11e7-9dc5-b6331d44f2b1.png)
![captura de pantalla 2017-10-05 a las 10 33 21](https://user-images.githubusercontent.com/454382/31217912-d56498a0-a9b8-11e7-9065-655b50bb2051.png)

**Comment by paucc** [comment]
It doesn't work either with the quote:

![screen shot 2017-10-05 at 10 43 37](https://user-images.githubusercontent.com/3023717/31218288-2a590f20-a9ba-11e7-8f5a-9212994b32e0.png)

**Comment by stadelmanma** [comment]
That is a shame word places those implicit restrictions but I suppose not surprising. I don't see too much of an issue with supporting insert fields with and without an equals sign if the latter could be turned off or on perhaps with a config option (off being the default).

That would fix your use case with the additional benefit of allowing someone with a large cache of old mail merge templates to use them "as-is" without having to go through an update every single merge field with an equals sign. It is turned off by default to avoid breaking the current expected behavior. Any thoughts on this @senny? 

Code Example: 
```ruby
# in your /config/application.rb or equivalent  file
Sablon.configure do |config|
  config.allow_insert_without_equals = true #false by default
end


# in lib/sablon/processor/document.rb
def consume(allow_insertion)
  @field = @fields.shift
  return unless @field
  case @field.expression
  when /^=/
    if allow_insertion
      Statement::Insertion.new(Expression.parse(@field.expression[1..-1]), @field)
    end
  when /([^ ]+):each\(([^ ]+)\)/
    block = consume_block("#{$1}:endEach")
    Statement::Loop.new(Expression.parse($1), $2, block)
  when /([^ ]+):if\(([^)]+)\)/
    block = consume_block("#{$1}:endIf")
    Statement::Condition.new(Expression.parse($1), block, $2)
  when /([^ ]+):if/
    block = consume_block("#{$1}:endIf")
    Statement::Condition.new(Expression.parse($1), block)
  when /comment/
    block = consume_block("endComment")
    Statement::Comment.new(block)
  else
    if allow_insertion && Sablon::Configuration.allow_insert_without_equals
      Statement::Insertion.new(Expression.parse(@field.expression), @field)
    end
  end
end
```

**Comment by senny** [comment]
The mindset behind sablon was that it is compatible with existing documents and doesn't interfere with whatever is already there. That's why I chose a distinct set of expressions from what you would see in regular MailMerge fields.

I can see that there are use-cases to use regular fields for insertion but I'm not fully convinced that sablon needs to address this use-case with a configuration option. What we could do though, is turn the whole case statement into a method. This would make it super easy to extend the behavior by using `Module.prepend` and `super`.

@stadelmanma what do you think?

**Comment by stadelmanma** [comment]
@senny I had to do some reading on `Module.preappend` as I wasn't familiar with it but I think I'm following. That sounds like a decent option to me since it'll make it easier for the end user to extend without doing awkward monkey patches or forking the gem.

**Comment by stadelmanma** [comment]
I am going to revisit this but from a slightly different angle. Instead of setting it up as a single method and using `Module.preappend` which is kind of hack-y and highly dependent on the implementation details. I am going to setup a formal API to register "merge field handlers".  

This will work in the exact same fashion as adding new DOM Handlers. You will specify the pattern to check and a method or proc to handle processing the fields. A "default" handler will made be available to take the place of an `else` clause in the above case statement when no other handler gets invoked. To match current the behaviors the default case would be a noop unless configured otherwise by the end user.

 In context of this specific issue you would copy the logic in the simple insertion handler over to the "default" handler to allow insertion without an equals sign.

The merge field handlers will probably accept the current instance of the document processor class (i.e. `self` in the above case statement), the current `@field` and the `allow_insertion` parameter. They would be expected to return a `Statement::*` class instance or something equivalent.

**Comment by stadelmanma** [comment]
Hi @skuark I don't know if or how you ended up solving this issue but the recently merged PR will allow you to easily accomplish this without  formal fork of the gem. I'm not going to cut a release yet but you can pull the gem from the master branch to try things out. 

See the [custom_field_handlers_test.rb](https://github.com/senny/sablon/blob/master/test/custom_field_handler_test.rb#L66) file for an example on how to add your own merge fields to Sablon.

**Comment by skuark** [comment]
Oh, great @stadelmanma, thanks a lot!

We didn't solve the issue yet, so I'll give a try as soon as I can.

**Comment by jrob00** [comment]
Ah nm! Got it! Thx for the feature @stadelmanma

**Comment by timkrins** [comment]
Just figured this out myself for this exact use case. Used

    class InsertionWithoutEqualsHandler < Sablon::Processor::Document::FieldHandler
      def initialize
        super(/^/)
      end

      def build_statement(_constructor, field, options = {})
        return unless options[:allow_insertion]

        expr = Sablon::Expression.parse(field.expression)
        Sablon::Statement::Insertion.new(expr, field)
      end
    end

    Sablon::Processor::Document.register_field_handler :insertion_without_equals, InsertionWithoutEqualsHandler.new

YMMV though - I am only using Sablon in a very very basic use-case.
