### ISSUE TITLE
Make URLs clickable in the generated File

### ISSUE THREAD

**Issue by ahmedelmahalawey** [senny/sablon#76]
Adding url in the text to be replaced doesn't get clickable when the file generated but when I open the docx file and set the cursor at the end of the url and press space or enter it gets clickable.

So is there a way to make the urls clickable in the generated file?

**Comment by stadelmanma** [comment]
Hi ahmed, URLs are tricky since they aren't stored solely in the document.xml file. They have a separate entry in the document.xml.rels file as well. Currently, we don't support hyperlinks for that reason because they are difficult to manage.

It is something we would like implement in the future and we would be glad to cooperate with you on a PR if you want to try and implement the feature yourself. 

There is some light discussion on about them in #48 and [this comment](https://github.com/senny/sablon/issues/47#issuecomment-299213891)

**Comment by ahmedelmahalawey** [comment]
Actually I tried to implement it using the configure option to implement <a> tag but I faced the same problem that it needs to add <Relation> tag in the document.xml.rels file.

Thanks anyways.
