### ISSUE TITLE
Tempfile Image

### ISSUE THREAD

**Issue by xinlangzi** [senny/sablon#93]
if the image is tempfile without postfix, 

```
logo = Tempfile.new('logo')
logo.binmode
logo.write(company.logo.read) rescue nil
logo.rewind
context = {
  image: Sablon.content(:image, logo.path)
}
```
then 
```
template.render_to_file(docx.path, context)
```
will broken.

```
stderr: Error: source file could not be loaded
```

**Comment by stadelmanma** [comment]
@xinlangzi thanks for bringing this up! As far as I know every file inside a MS Word document has to have a file extension (postfix) present in order for its content type system to work. This requirement was built into the image insertion feature of sablon since it will automatically add new content types on the fly. 

Although, I didn't think to test the case when an image was provided without an extension. If that is the only error message produced I'll make some adjustments so a more "verbose" message is provided indicating the real underlying problem.

To provide a little more context on why extensions are needed if you aren't familiar with the internals of a word doc here in a snippet from the `[Content_Types].xml` file.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="png" ContentType="image/png"/>
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  ...
</Types>
```

**Comment by stadelmanma** [comment]
@xinlangzi So I ran a few tests against our fixtures doing things the way you did with temp files and I was not able to reproduce the error. However, the larger issue is that tempfiles get a weird name that obscures  the  true extension, for example: `clone.jpg20180305-13153-1ej89dt` this causes the document to be corrupted. In hindsight I should raise an error when a valid extension doesn't exist so I'll make that adjustment in the next day or two. 

Lastly, to get around the temp file issue here is a workaround around that you might find suitable.
```ruby
logo = Tempfile.new('logo')
logo.write(company.logo.read)
logo.rewind
context = {
  image: Sablon.content(:image, logo, filename: 'logo.extension')
}
```
"extension" can be anything readable by MS Word (i.e. jpg, png, tiff, bmp, etc.) and using the `filename: ` optional argument will override the name provided to the temp file by default.
